/**
 * deploy.ts – Deploy and initialize the TokenForge token-burn-bridge Anchor program.
 *
 * Usage:
 *   ts-node scripts/deploy.ts devnet
 *   ts-node scripts/deploy.ts mainnet
 *
 * Prerequisites:
 *   1. `anchor build` – compiles the program and outputs the keypair to
 *      target/deploy/token_burn_bridge-keypair.json
 *   2. `solana config set --url <cluster>` – point your CLI to the target cluster
 *   3. Wallet at ~/.config/solana/id.json must have enough SOL for rent + fees
 *   4. EVM_RECEIVERS env var (JSON) – array of {chainId, receiverAddress, isActive}
 *      Example: export EVM_RECEIVERS='[{"chainId":2,"receiverAddress":"0x...","isActive":true}]'
 *
 * What this script does:
 *   a. Reads the deployed program ID from the keypair file.
 *   b. Calls the `initialize` instruction to set up the bridge config PDA.
 *   c. Prints the config PDA address and a summary of registered EVM chains.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider, Wallet, BN } from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  clusterApiUrl,
  Cluster,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
} from "@solana/spl-token";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

// ─── IDL & types (generated by `anchor build`) ────────────────────────────────
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require("../target/idl/token_burn_bridge.json");

// ─── Seeds ───────────────────────────────────────────────────────────────────
const BRIDGE_CONFIG_SEEDS = Buffer.from("bridge-config");

// ─── Default EVM receivers (Wormhole chain IDs) ───────────────────────────────
// These are placeholder addresses — replace with actual deployed BurnBridgeReceiver addresses.
const DEFAULT_EVM_RECEIVERS = [
  {
    chainId: 2,  // Ethereum
    receiverAddress: hexToBytes20(process.env.RECEIVER_MAINNET   ?? "0x0000000000000000000000000000000000000001"),
    isActive: true,
  },
  {
    chainId: 4,  // BSC
    receiverAddress: hexToBytes20(process.env.RECEIVER_BSC       ?? "0x0000000000000000000000000000000000000002"),
    isActive: true,
  },
  {
    chainId: 5,  // Polygon
    receiverAddress: hexToBytes20(process.env.RECEIVER_POLYGON   ?? "0x0000000000000000000000000000000000000003"),
    isActive: true,
  },
  {
    chainId: 23, // Arbitrum
    receiverAddress: hexToBytes20(process.env.RECEIVER_ARBITRUM  ?? "0x0000000000000000000000000000000000000004"),
    isActive: true,
  },
  {
    chainId: 30, // Base
    receiverAddress: hexToBytes20(process.env.RECEIVER_BASE      ?? "0x0000000000000000000000000000000000000005"),
    isActive: true,
  },
  {
    chainId: 6,  // Avalanche
    receiverAddress: hexToBytes20(process.env.RECEIVER_AVALANCHE ?? "0x0000000000000000000000000000000000000006"),
    isActive: true,
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function hexToBytes20(hex: string): number[] {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  return Array.from(Buffer.from(clean.padStart(40, "0").slice(0, 40), "hex"));
}

function loadKeypair(filePath: string): Keypair {
  const expanded = filePath.startsWith("~")
    ? path.join(os.homedir(), filePath.slice(1))
    : filePath;
  const raw = JSON.parse(fs.readFileSync(expanded, "utf-8")) as number[];
  return Keypair.fromSecretKey(Uint8Array.from(raw));
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const clusterArg = (process.argv[2] ?? "devnet") as Cluster | "localnet";
  const clusterUrl =
    clusterArg === "localnet"
      ? "http://127.0.0.1:8899"
      : clusterApiUrl(clusterArg as Cluster);

  console.log(`\n🔥 TokenForge BurnBridge – Solana deploy`);
  console.log(`   Cluster : ${clusterArg} (${clusterUrl})`);

  // ── Load wallet ─────────────────────────────────────────────────────────────
  const walletPath =
    process.env.ANCHOR_WALLET ??
    path.join(os.homedir(), ".config", "solana", "id.json");
  const walletKeypair = loadKeypair(walletPath);
  const wallet        = new Wallet(walletKeypair);

  console.log(`   Wallet  : ${wallet.publicKey.toBase58()}`);

  const connection = new Connection(clusterUrl, "confirmed");
  const provider   = new AnchorProvider(connection, wallet, { commitment: "confirmed" });
  anchor.setProvider(provider);

  // ── Load program ────────────────────────────────────────────────────────────
  const programKeypairPath = path.join(
    __dirname,
    "..",
    "target",
    "deploy",
    "token_burn_bridge-keypair.json"
  );
  const programKeypair = loadKeypair(programKeypairPath);
  const programId      = programKeypair.publicKey;

  console.log(`   Program : ${programId.toBase58()}`);

  const program = new Program(IDL, programId, provider) as unknown as Program<any>;

  // ── Parse EVM receivers ─────────────────────────────────────────────────────
  let evmReceivers = DEFAULT_EVM_RECEIVERS;
  if (process.env.EVM_RECEIVERS) {
    try {
      const parsed = JSON.parse(process.env.EVM_RECEIVERS) as Array<{
        chainId: number;
        receiverAddress: string;
        isActive: boolean;
      }>;
      evmReceivers = parsed.map((r) => ({
        chainId:         r.chainId,
        receiverAddress: hexToBytes20(r.receiverAddress),
        isActive:        r.isActive,
      }));
      console.log(`   Using ${evmReceivers.length} receivers from EVM_RECEIVERS env var`);
    } catch {
      console.warn("   Warning: could not parse EVM_RECEIVERS — using defaults");
    }
  }

  // ── Derive config PDA ───────────────────────────────────────────────────────
  const [configPda, configBump] = PublicKey.findProgramAddressSync(
    [BRIDGE_CONFIG_SEEDS],
    programId
  );
  console.log(`   Config PDA  : ${configPda.toBase58()} (bump ${configBump})`);

  // ── Check if already initialized ────────────────────────────────────────────
  const existingConfig = await program.account.bridgeConfig.fetchNullable(configPda);
  if (existingConfig) {
    console.log("\n✅ Bridge config already initialized!");
    printConfigSummary(existingConfig);
    return;
  }

  // ── Determine token mint ─────────────────────────────────────────────────────
  let tokenMint: PublicKey;

  if (process.env.TOKEN_MINT) {
    tokenMint = new PublicKey(process.env.TOKEN_MINT);
    console.log(`   Token mint  : ${tokenMint.toBase58()} (from TOKEN_MINT env var)`);
  } else {
    console.log("\n⚠️  No TOKEN_MINT env var set — creating a new SPL token mint for testing.");
    tokenMint = await createMint(
      connection,
      walletKeypair,
      wallet.publicKey,
      null,
      9
    );
    console.log(`   Token mint  : ${tokenMint.toBase58()} (newly created)`);
    console.log(`   → Set TOKEN_MINT=${tokenMint.toBase58()} in .env for future runs`);
  }

  // ── Call initialize ──────────────────────────────────────────────────────────
  console.log("\nCalling initialize…");

  const txSig = await program.methods
    .initialize(evmReceivers)
    .accounts({
      config:        configPda,
      tokenMint,
      authority:     wallet.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  console.log(`✅ Bridge initialized!`);
  console.log(`   Tx  : ${txSig}`);
  if (clusterArg === "devnet") {
    console.log(`   Explorer: https://explorer.solana.com/tx/${txSig}?cluster=devnet`);
  }

  const config = await program.account.bridgeConfig.fetch(configPda);
  printConfigSummary(config);

  // ── Print env vars for frontend ─────────────────────────────────────────────
  console.log("\n=== Add to frontend/.env.local ===");
  console.log(`NEXT_PUBLIC_SOLANA_BURN_BRIDGE_PROGRAM_ID=${programId.toBase58()}`);
  console.log(`# Bridge config PDA: ${configPda.toBase58()}`);
}

function printConfigSummary(config: any) {
  console.log("\n=== Bridge Config ===");
  console.log(`Authority     : ${config.authority.toBase58()}`);
  console.log(`Token mint    : ${config.tokenMint.toBase58()}`);
  console.log(`Total burned  : ${config.totalBurned.toString()}`);
  console.log(`Messages sent : ${config.totalMessagesSent.toString()}`);
  console.log("\nRegistered EVM receivers:");
  for (const r of config.evmReceivers) {
    const addrHex = "0x" + Buffer.from(r.receiverAddress).toString("hex");
    const chainNames: Record<number, string> = {
      2: "Ethereum", 4: "BSC", 5: "Polygon",
      6: "Avalanche", 23: "Arbitrum", 30: "Base",
    };
    const name = chainNames[r.chainId] ?? `Chain ${r.chainId}`;
    console.log(
      `  [${r.chainId.toString().padStart(3)}] ${name.padEnd(12)} ${addrHex} ${r.isActive ? "✓ active" : "✗ inactive"}`
    );
  }
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("\n❌ Deploy failed:", err);
    process.exit(1);
  });
